# Generated by Django 5.0.7 on 2024-11-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(default="User", max_length=30),
        ),
    ]
